[package]
name = "stacks_exchange"
version = "0.1.0"
authors = ["David Simon <D@vidSimon.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
pretty_env_logger = "0.4"
serde = "1"
serde_json = "1"
juniper = "0.14"
