name: Rust

on:
  push:
    branches: [ master ]
    paths: [ 'server/*' ]
  pull_request:
    branches: [ master ]
    paths: [ 'server/*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      uses: actions-rs/clippy-check@v1
    - name: Build
      run: cargo build --verbose
      working-directory: server
    - name: Run tests
      run: cargo test --verbose
      working-directory: server
